name: ngbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull the Docker image
        run: docker pull angular/ngcontainer
      - name: docker run
        run: |
           docker container run angular/ngcontainer
      - name: Install dependencies
        run: |
             mkdir Downloads
             cd Download
             echo 'npm install'
             echo 'npm run ng build --prod'
             cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: download-file
          path: Downloads
    
    
