name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: pull the Docker image
      run: docker pull amazon/aws-lambda-nodejs:latest
    - name: docker build 
      run: docker build -it amazon/aws-lambda-nodejs:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: login
      run: echo "login success"
    - name: tag
      run:  docker tag amazon/aws-lambda-nodejs sindhu530/dockerhub:myfirstimagepush
    - name: push
      run: docker push sindhu530/dockerhub:myfirstimagepush
   
    
    
