
name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
    
  Build:
      uses:
        sindhura530/ActionTest/.github/workflows/secondFile.yml@main
  Build1:
    uses:
      sindhura530/ActionTest/.github/workflows/npm.yml@main
      

   
      
      

  
       
  Build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'sindhu'    > sindhu.html
          echo 'chaitra'    > chaitra.html
          echo 'ramya'  > ramya.html
          cd ..
    
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
        
      
  Dev-deploy:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://github.com/sindhura530/github-workflows/tree/feature'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
        
  Stage-deploy:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging 
      url: 'https://github.com/sindhura530/github-workflows/tree/develop'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  Prod-deploy:
    name: Deploy to Production 
    needs: [Stage-deploy]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'https://github.com/sindhura530/github-workflows/tree/main'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
       
  
