
name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
    
  Build-Ubuntu:
      uses:
        sindhura530/ActionTest/.github/workflows/secondFile.yml@main
  
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          echo 'bravo'    > bravo.html
          echo 'charlie'  > charlie.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
        
      
  Dev-deployment:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build-Ubuntu]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://github.com/sindhura530/github-workflows/tree/feature'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build-Ubuntu]
    runs-on: ubuntu-latest
    environment: 
      name: Staging 
      url: 'https://github.com/sindhura530/github-workflows/tree/develop'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'https://github.com/sindhura530/github-workflows/tree/main'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
       
  
