
name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
    
  build:
      uses:
        sindhura530/ActionTest/.github/workflows/secondFile.yml@main
        
      
  deployment:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://github.com/sindhura530/github-workflows/tree/feature'
    steps:
      - name: Deploy
        run: echo I am deploying!
       
  
