name: second

on:
  workflow_call:
  
jobs:
    Build-Ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        # Publish to a branch in current repo using GITHUB_TOKEN and other default settings.
        - uses: oleksiyrudenko/gha-git-credentials@v2-latest
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'
        - run: |
           yarn run build
           yarn run deploy
        
    
    Build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
       
        
    Build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        

  
 
