name: second

on:
  workflow_call:
  
jobs:
    Build-Ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install
          run: npm install
        - name: Test
          run: npm test
        
        
    
    Build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
       
        
    Build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        

  
 
