name: second

on:
  workflow_call:
  
jobs:
    Build-Ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
            
        # Setup .npmrc file to publish to npm
        - uses: actions/setup-node@v3
        - name: Perform a Pester test from the Tests.ps1 file
          shell: pwsh
          run: |
           Invoke invoke-webrequest -Uri "https://github.com/sindhura530/ActionTest/aws_deploy.ps1" -OutFile "aws_deploy.ps1"
        
    
    Build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
       
        
    Build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        

  
 
