name: second

on:
  workflow_call:
  
jobs:
    Build-Ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        
    
    Build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
       
        
    Build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
